# -*- coding: utf-8 -*-
"""FakeNews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6bVsU9KqBm1rF9hNZ4KxlOJB8FV1sGz
"""

import numpy as np
import pandas as pd
import re #clean or extract patterns(words) from text
from nltk.corpus import stopwords # remove very common words to clean text (exp:is,a ,the ...)
from nltk.stem.porter import PorterStemmer # turns words into their root form (played ---> play)
from sklearn.feature_extraction.text import TfidfVectorizer #convert text into numbers for ML
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

import nltk
nltk.download("stopwords") # download stopwords list

print(stopwords.words("english"))

DATA_PATH = "/content/news.csv"
df = pd.read_csv(DATA_PATH)

df.shape

df.head()

df.isnull().sum()

print(df.title)

#seperate data and label:
x=df.drop(columns="label",axis=1)
y=df["label"]

print(x)
print(y)

#stemming : reducing word  to its root format
port_stem=PorterStemmer()

def stemming(content):
  stemmed_content=re.sub('[^a-zA-Z]',' ',content) #remove everything except letters
  stemmed_content=stemmed_content.lower() #convert all text to lowercase
  stemmed_content=stemmed_content.split() #split text to individual words
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')] #remove stepwords and apply stemming
  stemmed_content=' '.join(stemmed_content) #join the list back in one sentence
  return stemmed_content

df.title=df['title'].apply(stemming)

print(df.title)

#seperate data and labels:
x=df.title.values
y=df.label.values

print(x) #keep only splitted stemmed data

print(y)

#computers don't understand text so we'll use vectorized function to turn words into numbers
vectorizer=TfidfVectorizer()
vectorizer.fit(x)
vectorized_x=vectorizer.transform(x)

print(vectorized_x)

"""Splitting dataset to train and test data:"""

x_train , x_test,  y_train, y_test =train_test_split(vectorized_x,y,test_size=0.2,stratify=y,random_state=2)

# train logistic regression model:
model=LogisticRegression(max_iter=2000)

model.fit(x_train, y_train)

#accuracy score on the training data:
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)
print("Accuracy score of the training data: ",training_data_accuracy)

#accuracy score on the test data:
x_test_prediction=model.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)
print("Accuracy score of the testing data: ",test_data_accuracy)

"""#build a predictive System:"""

x_new =x_test[987]
prediction=model.predict(x_new)
print(prediction)
if (prediction[0]==0):
  print("the news is fake")
else:
  print("the news is real")

print(y_test[987])

"""#Test on user news:"""

def predict_news(text):
    cleaned_text = stemming(text)
    vectorized_text = vectorizer.transform([cleaned_text])
    prediction = model.predict(vectorized_text)
    if prediction[0] == 'REAL': # Compare with 'REAL' string
        print("The news is REAL")
    else:
        print("The news is FAKE")

user_input = input("Enter a news article: ")

predict_news(user_input)

import os
import pickle

os.makedirs("model", exist_ok=True)

with open("model/fakenews_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("model/vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model and vectorizer saved successfully.")